version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: purein_task
      POSTGRES_USER: purein_admin
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
